# Generated by Django 5.2.5 on 2025-08-26 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True)),
                ('reco_type', models.CharField(choices=[('Temperature', 'Temperature'), ('Spo2', 'Spo2'), ('Heart', 'Heart'), ('Respiration', 'Respiration'), ('Pressure', 'Pressure')], max_length=20)),
                ('context', models.CharField(choices=[('Home', 'Home'), ('Hospital', 'Hospital'), ('Ambulatory', 'Ambulatory'), ('Any', 'Any')], default='Any', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_id', models.IntegerField()),
                ('sp_id', models.IntegerField()),
                ('pr_id', models.IntegerField()),
                ('bt_id', models.IntegerField()),
                ('resp_id', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'indexes': [models.Index(fields=['hr_id', 'sp_id', 'pr_id', 'bt_id', 'resp_id'], name='knowledge_a_hr_id_5509b2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_no', models.IntegerField(default=1)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='knowledge.anomaly')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medications', to='knowledge.recommendation')),
            ],
            options={
                'indexes': [models.Index(fields=['diagnosis', 'sequence_no'], name='knowledge_m_diagnos_56ee26_idx')],
                'unique_together': {('diagnosis', 'recommendation')},
            },
        ),
        migrations.CreateModel(
            name='ExceptionDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='knowledge.patienthealth')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='knowledge.recommendation')),
            ],
            options={
                'unique_together': {('recommendation', 'health')},
            },
        ),
    ]
