# Generated by Django 5.0.6 on 2025-09-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('sensorTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Sensor Type',
                'verbose_name_plural': 'Sensor Types',
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('readingID', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deviceID', models.ForeignKey(blank=True, db_column='deviceID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='farms.device')),
                ('sensor_typeID', models.ForeignKey(blank=True, db_column='sensor_typeID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensortype')),
            ],
            options={
                'verbose_name': 'Reading',
                'verbose_name_plural': 'Readings',
                'indexes': [models.Index(fields=['deviceID', 'timestamp'], name='sensors_rea_deviceI_445814_idx')],
            },
        ),
    ]
