# Generated by Django 5.0.6 on 2025-09-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'ordering': ['-timestamp', 'readingID'], 'verbose_name': 'Reading', 'verbose_name_plural': 'Readings'},
        ),
    ]
