# Generated by Django 5.2.5 on 2025-09-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeds', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchID', models.IntegerField(unique=True)),
                ('arriveDate', models.DateField(default='1900-01-01')),
                ('initAge', models.IntegerField(default=0)),
                ('harvestAge', models.IntegerField(default=0)),
                ('quanitity', models.IntegerField(default=0)),
                ('initWeight', models.IntegerField(default=0)),
                ('batch_status', models.IntegerField(default=1)),
                ('breedID', models.ForeignKey(blank=True, db_column='breedID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='breeds.breed')),
                ('farmID', models.ForeignKey(blank=True, db_column='farmID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityID', models.IntegerField(unique=True)),
                ('activityName', models.CharField(default='Default Activity', max_length=100)),
                ('activityDescription', models.CharField(default='No description', max_length=300)),
                ('activityDay', models.CharField(default='Day', max_length=10)),
                ('activity_status', models.IntegerField(default=1)),
                ('activity_frequency', models.IntegerField(default=1)),
                ('batchID', models.ForeignKey(blank=True, db_column='batchID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='batches.batch')),
            ],
        ),
        migrations.CreateModel(
            name='BatchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchActivityID', models.IntegerField(default=0, unique=True)),
                ('batchActivityName', models.CharField(default='Default Batch Activity', max_length=100)),
                ('batchActivityDate', models.DateField(default='1900-01-01')),
                ('batchActivityDetails', models.CharField(default='No details', max_length=50)),
                ('batchAcitivtyCost', models.IntegerField(default=0)),
                ('batchID', models.ForeignKey(blank=True, db_column='batchID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='batches.batch')),
                ('breedActivityID', models.ForeignKey(blank=True, db_column='breedActivityID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_activities', to='breeds.breedactivity')),
            ],
        ),
        migrations.CreateModel(
            name='BatchFeeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchFeedingID', models.IntegerField(unique=True)),
                ('feedingDate', models.DateField(default='CURRENT_DATE')),
                ('feedingAmount', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('batchID', models.ForeignKey(blank=True, db_column='batchID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='batches.batch')),
            ],
        ),
    ]
