# Generated by Django 5.0.6 on 2025-09-11 11:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeds', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchID', models.AutoField(db_column='batchID', primary_key=True, serialize=False)),
                ('arriveDate', models.DateField(default=django.utils.timezone.now)),
                ('initAge', models.PositiveIntegerField(default=0)),
                ('harvestAge', models.PositiveIntegerField(default=0)),
                ('quanitity', models.PositiveIntegerField(default=0)),
                ('initWeight', models.PositiveIntegerField(default=0)),
                ('batch_status', models.SmallIntegerField(default=1)),
                ('breedID', models.ForeignKey(blank=True, db_column='breedID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='breeds.breed')),
                ('farmID', models.ForeignKey(blank=True, db_column='farmID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('activityID', models.AutoField(db_column='activityID', primary_key=True, serialize=False)),
                ('activityName', models.CharField(max_length=100)),
                ('activityDescription', models.CharField(blank=True, default='', max_length=300)),
                ('activityDay', models.CharField(max_length=10)),
                ('activity_status', models.SmallIntegerField(default=1)),
                ('activity_frequency', models.PositiveIntegerField(default=1)),
                ('batchID', models.ForeignKey(blank=True, db_column='batchID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='batches.batch')),
            ],
            options={
                'verbose_name': 'Activity Schedule',
                'verbose_name_plural': 'Activity Schedules',
            },
        ),
        migrations.CreateModel(
            name='BatchActivity',
            fields=[
                ('batchActivityID', models.AutoField(db_column='batchActivityID', primary_key=True, serialize=False)),
                ('batchActivityName', models.CharField(max_length=100)),
                ('batchActivityDate', models.DateField(default=django.utils.timezone.now)),
                ('batchActivityDetails', models.CharField(blank=True, default='', max_length=100)),
                ('batchAcitivtyCost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('batchID', models.ForeignKey(blank=True, db_column='batchID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='batches.batch')),
                ('breedActivityID', models.ForeignKey(blank=True, db_column='breedActivityID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_activities', to='breeds.breedactivity')),
            ],
            options={
                'verbose_name': 'Batch Activity',
                'verbose_name_plural': 'Batch Activities',
            },
        ),
        migrations.CreateModel(
            name='BatchFeeding',
            fields=[
                ('batchFeedingID', models.AutoField(db_column='batchFeedingID', primary_key=True, serialize=False)),
                ('feedingDate', models.DateField(default=django.utils.timezone.now)),
                ('feedingAmount', models.PositiveIntegerField(default=0)),
                ('status', models.SmallIntegerField(default=1)),
                ('batchID', models.ForeignKey(blank=True, db_column='batchID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='batches.batch')),
            ],
            options={
                'verbose_name': 'Batch Feeding',
                'verbose_name_plural': 'Batch Feedings',
            },
        ),
    ]
