# Generated by Django 5.2.5 on 2025-08-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breeds', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_date', models.DateField()),
                ('init_age', models.IntegerField()),
                ('harvest_age', models.IntegerField(default=0)),
                ('quantity', models.IntegerField()),
                ('init_weight', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Ongoing'), (2, 'Completed')], default=1)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='breeds.breed')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='BatchActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=200)),
                ('cost', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='batches.batch')),
                ('breed_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_activities', to='breeds.breedactivity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('period', models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], default='Day', max_length=10)),
                ('frequency', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='batches.batch')),
            ],
            options={
                'unique_together': {('batch', 'name')},
            },
        ),
    ]
