# Generated by Django 5.0.6 on 2025-09-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'ordering': ['-arriveDate', 'batchID'], 'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
    ]
