# Generated by Django 5.0.6 on 2025-09-10 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityschedule',
            options={'verbose_name': 'Activity Schedule', 'verbose_name_plural': 'Activity Schedules'},
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='batchactivity',
            options={'verbose_name': 'Batch Activity', 'verbose_name_plural': 'Batch Activities'},
        ),
        migrations.AlterModelOptions(
            name='batchfeeding',
            options={'verbose_name': 'Batch Feeding', 'verbose_name_plural': 'Batch Feedings'},
        ),
    ]
