# Generated by Django 5.0.6 on 2025-09-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityschedule',
            name='activity_status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (9, 'Archived')], default=1),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (9, 'Archived')], default=1),
        ),
        migrations.AlterField(
            model_name='batchfeeding',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (9, 'Archived')], default=1),
        ),
    ]
