# Generated by Django 5.2.5 on 2025-08-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BreedType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('photo', models.CharField(default='preedphoto.png', max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeds', to='breeds.breedtype')),
            ],
        ),
        migrations.CreateModel(
            name='BreedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breed_activities', to='breeds.activitytype')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='breeds.breed')),
            ],
            options={
                'unique_together': {('breed', 'activity_type', 'age')},
            },
        ),
        migrations.CreateModel(
            name='BreedGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('min_weight', models.IntegerField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth', to='breeds.breed')),
            ],
            options={
                'unique_together': {('breed', 'age')},
            },
        ),
        migrations.CreateModel(
            name='BreedCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='breeds.breed')),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breed_conditions', to='breeds.conditiontype')),
            ],
            options={
                'unique_together': {('breed', 'condition_type')},
            },
        ),
        migrations.CreateModel(
            name='BreedFeeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('frequency', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_rules', to='breeds.breed')),
                ('food_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breed_feeding', to='breeds.foodtype')),
            ],
            options={
                'unique_together': {('breed', 'food_type', 'age')},
            },
        ),
    ]
