# Generated by Django 5.0.6 on 2025-09-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='preedphoto',
            field=models.CharField(blank=True, default='preedphoto.png', max_length=255, null=True),
        ),
    ]
