# Generated by Django 5.0.6 on 2025-09-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breedactivity',
            name='breed_activity_status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (9, 'Archived')], default=1),
        ),
        migrations.AlterField(
            model_name='breedcondition',
            name='condition_status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (9, 'Archived')], default=1),
        ),
        migrations.AlterField(
            model_name='breedfeeding',
            name='breed_feed_status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive'), (9, 'Archived')], default=1),
        ),
        migrations.AddIndex(
            model_name='breedgrowth',
            index=models.Index(fields=['breedID', 'age'], name='breed_growth_age_idx'),
        ),
    ]
