# Generated by Django 5.0.6 on 2025-09-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0002_alter_breed_preedphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breedactivity',
            options={'ordering': ['breedID', 'age'], 'verbose_name': 'Breed Activity', 'verbose_name_plural': 'Breed Activities'},
        ),
    ]
