# Generated by Django 5.0.6 on 2025-09-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0003_alter_breedactivity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breedcondition',
            options={'ordering': ['breedID', 'condition_typeID'], 'verbose_name': 'Breed Condition', 'verbose_name_plural': 'Breed Conditions'},
        ),
        migrations.AlterModelOptions(
            name='breedfeeding',
            options={'ordering': ['breedID', 'age', 'foodTypeID'], 'verbose_name': 'Breed Feeding', 'verbose_name_plural': 'Breed Feedings'},
        ),
        migrations.AlterModelOptions(
            name='breedgrowth',
            options={'ordering': ['breedID', 'age'], 'verbose_name': 'Breed Growth', 'verbose_name_plural': 'Breed Growths'},
        ),
    ]
