# Generated by Django 5.2.5 on 2025-08-26 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('resource_type', models.IntegerField(choices=[(1, 'Smart Device'), (2, 'Software Feature'), (3, 'Data Analytics'), (4, 'Predictions')], default=1)),
                ('unit_cost', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('farm_size', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.farmer')),
                ('sub_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmer_subscriptions', to='subscriptions.subscriptiontype')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('pay_date', models.DateField()),
                ('receipt', models.CharField(default='no_receipt.jpg', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('farmer_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.farmersubscription')),
            ],
        ),
        migrations.CreateModel(
            name='FarmerSubscriptionResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.BooleanField(default=True)),
                ('farmer_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='subscriptions.farmersubscription')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='subscriptions.resource')),
            ],
            options={
                'unique_together': {('farmer_subscription', 'resource')},
            },
        ),
    ]
