# Generated by Django 5.0.6 on 2025-09-02 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmersubscription',
            options={'ordering': ['-start_date'], 'verbose_name': 'Farmer Subscription', 'verbose_name_plural': 'Farmer Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='farmersubscriptionresource',
            options={'verbose_name': 'Subscription Resource', 'verbose_name_plural': 'Subscription Resources'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['resource_type', 'name']},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='pay_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='farmersubscription',
            name='discount',
        ),
        migrations.AddField(
            model_name='farmersubscription',
            name='auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmersubscription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='farmersubscriptionresource',
            name='allocated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmersubscriptionresource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('FEEDING', 'Feeding Node'), ('THERMAL', 'Thermal Node'), ('WATERING', 'Watering Node'), ('WEIGHTING', 'Weighting Node'), ('DUSTING', 'Dusting Node'), ('PREDICTION', 'Prediction Service'), ('ANALYTICS', 'Analytics Service'), ('INVENTORY', 'Inventory Management')], default='INVENTORY', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_basic',
            field=models.BooleanField(default=False, help_text='If True, this resource is available to all farmers regardless of subscription'),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='includes_analytics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='includes_predictions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='max_hardware_nodes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='max_software_services',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='tier',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual/Small'), ('NORMAL', 'Normal/Medium'), ('PREMIUM', 'Premium/Large')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmersubscription',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='farmersubscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending Payment'), ('SUSPENDED', 'Suspended'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmersubscriptionresource',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payments/receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('HARDWARE', 'Hardware Node'), ('SOFTWARE', 'Software Service'), ('PREDICTION', 'Prediction Service'), ('ANALYTICS', 'Analytics Service')], default='HARDWARE', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptiontype',
            name='description',
            field=models.TextField(),
        ),
    ]
