# Generated by Django 5.0.6 on 2025-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='farmersubscription',
            index=models.Index(fields=['status', 'start_date'], name='subscription_status_start_idx'),
        ),
        migrations.AddIndex(
            model_name='farmersubscriptionresource',
            index=models.Index(fields=['status'], name='sub_res_status_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['resource_type', 'category'], name='resource_type_category_idx'),
        ),
    ]
