# Generated by Django 5.0.6 on 2025-09-13 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_farmersubscription_subscription_status_start_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='subscription_resources',
            field=models.ManyToManyField(help_text='Subscriptions that use this resource', related_name='resource_allocations', through='subscriptions.FarmerSubscriptionResource', to='subscriptions.farmersubscription'),
        ),
        migrations.AlterField(
            model_name='farmersubscriptionresource',
            name='farmerSubscriptionID',
            field=models.ForeignKey(blank=True, db_column='farmerSubscriptionID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_resources', to='subscriptions.farmersubscription'),
        ),
    ]
