# Generated by Django 5.0.6 on 2025-09-11 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farmID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=20)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='accounts.farmer')),
            ],
            options={
                'verbose_name': 'Farm',
                'verbose_name_plural': 'Farms',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceID', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('cell_no', models.CharField(default='none', max_length=20)),
                ('picture', models.CharField(default='device_default.png', max_length=50)),
                ('status', models.BooleanField(default=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='farms.farm')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
