# Generated by Django 5.0.6 on 2025-09-17 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='farmerID',
        ),
        migrations.CreateModel(
            name='FarmMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('WORKER', 'Worker')], max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.farmer')),
            ],
            options={
                'db_table': 'farm_membership_tb',
                'unique_together': {('farmer', 'farm')},
            },
        ),
    ]
